version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/mycelium"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    # Enable security updates
    security-updates-only: true

  # Backend API dependencies
  - package-ecosystem: "pip"
    directory: "/backend/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
    security-updates-only: true

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/mycelium"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    security-updates-only: true

  - package-ecosystem: "docker"
    directory: "/backend/api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    security-updates-only: true

  - package-ecosystem: "docker"
    directory: "/backend/keycloak"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    security-updates-only: true

  - package-ecosystem: "docker"
    directory: "/backend/database"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    security-updates-only: true

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    security-updates-only: true 