services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PORT=${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
      args:
        - KC_PORT=${KC_PORT}
        - KC_MANAGEMENT_PORT=${KC_MANAGEMENT_PORT}
        - KC_REALM=${KC_REALM}
        - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - FRONTEND_HOST=${FRONTEND_HOST}
        - FRONTEND_PORT=${FRONTEND_PORT}
    environment:
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_CLIENT_ID=${KC_CLIENT_ID}
      - KC_GOOGLE_CLIENT_ID=${KC_GOOGLE_CLIENT_ID}
      - KC_GOOGLE_CLIENT_SECRET=${KC_GOOGLE_CLIENT_SECRET}
    ports:
      - "${KC_PORT}:8080"
      - "${KC_MANAGEMENT_PORT}:9000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/scripts/healthcheck.sh"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db:
networks:
  app-network:
    driver: bridge
