test:
  unit:
    coverage:
      threshold: 80
    timeout_minutes: 30
    env:
      NODE_ENV: test
      PYTHON_ENV: test
      JAVA_OPTS: "-Dtest.env=true"
  integration:
    coverage:
      threshold: 70
    timeout_minutes: 60
    env:
      NODE_ENV: test
      PYTHON_ENV: test
      JAVA_OPTS: "-Dtest.env=true" 