name: Build Workflow

permissions:
  contents: read
  packages: write      # Pour push des images
  security-events: write  # Pour Trivy

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
        description: 'JSON array of services to build'
    outputs:
      image_tags:
        description: "JSON object mapping services to their image tags"
        value: ${{ jobs.build.outputs.image_tags }}
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  REGISTRY: docker.io
  REPOSITORY: myceliumai # Remplacez par votre nom d'organisation Docker

jobs:
  prepare:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    outputs:
      build_date: ${{ steps.prep.outputs.build_date }}
      version: ${{ steps.prep.outputs.version }}
    steps:
      - id: prep
        run: |
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

  build:
    permissions:
      contents: read
      packages: write
      security-events: write
    needs: [prepare]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        service: ${{ fromJson(inputs.matrix) }}
      fail-fast: false
    
    outputs:
      image_tags: ${{ steps.image-tags.outputs.tags }}

    steps:
      - uses: actions/checkout@v4.1.1  # Déjà à jour
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18  # v3.0.0
        with:
          platforms: 'amd64,arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2b9a1c10f2d4e5840e6b956488e5c3a4765df3d7  # v3.1.0

      - name: Cache Docker layers
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2  # v4.0.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}-
            
      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20  # v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Image Tags
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81  # v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ matrix.service }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.prepare.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.prepare.outputs.version }}
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.created=${{ needs.prepare.outputs.build_date }}
            org.opencontainers.image.version=${{ needs.prepare.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and Push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56  # v5.1.0
        with:
          context: ./${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILD_DATE=${{ needs.prepare.outputs.build_date }}
            VERSION=${{ needs.prepare.outputs.version }}
            COMMIT_SHA=${{ github.sha }}
          
      # Temp fix for cache
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Record Image Tags
        id: image-tags
        run: |
          TAGS=$(echo '${{ steps.meta.outputs.json }}' | jq -c .)
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Scan Image
        uses: aquasecurity/trivy-action@d43c1f16c00cfd3978dde6c07f4bbcf9eb6993ca  # v0.17.0
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Scan Results
        uses: github/codeql-action/upload-sarif@1b1aada464948af03b950897e5eb522f92603cc2  # v3.24.6
        with:
          sarif_file: 'trivy-results.sarif'
          category: trivy-${{ matrix.service }}