name: CI/CD Pipeline

permissions:
  contents: read
  pull-requests: read
  packages: write    # Pour le push des images Docker
  security-events: write  # Pour les résultats de scan Trivy

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  changes:
    uses: ./.github/workflows/reusable/changes.yaml
    permissions:
      contents: read
      pull-requests: read
    secrets: inherit

  tests:
    needs: [changes]
    uses: ./.github/workflows/reusable/tests.yaml
    with:
      matrix: ${{ needs.changes.outputs.matrix }}
    secrets: inherit

  build:
    needs: [tests]
    if: |
      github.event_name == 'push' && 
      (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    uses: ./.github/workflows/reusable/build.yaml
    with:
      matrix: ${{ needs.changes.outputs.matrix }}
    secrets: inherit