name: CI/CD Pipeline

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  changes:
    uses: ./.github/workflows/changes.yaml
    permissions:
      contents: read
      pull-requests: read
    secrets: inherit

  tests:
    needs: [changes]
    uses: ./.github/workflows/tests.yaml
    with:
      matrix: ${{ needs.changes.outputs.matrix }}
    secrets: inherit

  build:
    needs: [tests]
    if: |
      github.event_name == 'push' && 
      (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    uses: ./.github/workflows/build.yaml
    with:
      matrix: ${{ needs.changes.outputs.matrix }}
    secrets: inherit