name: CI/CD Pipeline

# Add default permissions for all jobs
permissions: {}  # Default to no permissions

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  REPOSITORY: myceliumai
  FRONTEND_IMAGE: myceliumai/frontend
  API_IMAGE: myceliumai/api
  KEYCLOAK_IMAGE: myceliumai/keycloak
  DB_IMAGE: myceliumai/database

jobs:
  changes:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
      contents: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      api: ${{ steps.filter.outputs.api }}
      keycloak: ${{ steps.filter.outputs.keycloak }}
      database: ${{ steps.filter.outputs.database }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: |
            frontend:
              - 'mycelium/**'
              - '.github/workflows/**'
            api:
              - 'backend/api/**'
              - '.github/workflows/**'
            keycloak:
              - 'backend/keycloak/**'
              - '.github/workflows/**'
            database:
              - 'backend/database/**'
              - '.github/workflows/**'

  frontend-checks:
    needs: [changes]
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    name: Frontend Checks
    runs-on: ubuntu-22.04
    permissions:
      contents: read      # Only needs to read repository contents
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      
      - name: Set up Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'mycelium/yarn.lock'

      - name: Install dependencies
        working-directory: ./mycelium
        run: yarn install

      - name: Run linting
        working-directory: ./mycelium
        run: yarn lint || true

      - name: Run tests
        working-directory: ./mycelium
        run: yarn test || true

  keycloak-checks:
    needs: [changes]
    if: ${{ needs.changes.outputs.keycloak == 'true' }}
    name: Keycloak Checks
    runs-on: ubuntu-22.04
    permissions:
      contents: read      # Only needs to read repository contents
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      
      - name: Lint shell scripts
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck backend/keycloak/scripts/*.sh

  security:
    name: Security Checks
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
      pull-requests: read
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      # Scan for vulnerabilities including dependencies
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          scanners: 'vuln,secret,config'  # Enable vulnerability scanning for dependencies

      # Upload scan results
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy'

  api-checks:
    needs: [changes]
    if: ${{ needs.changes.outputs.api == 'true' }}
    name: API Checks
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write  # Needed for code coverage comments
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v4.1.1
    
    - name: Set up Python
      uses: actions/setup-python@39cd149b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0
      with:
        python-version: '3.10'
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false
        
    - name: Install dependencies
      run: |
        cd backend/api
        poetry install
        
    - name: Run code formatting check
      run: |
        cd backend/api
        poetry run ruff format . --check
        
    - name: Run linting check
      run: |
        cd backend/api
        poetry run ruff check .

    - name: Run unit tests
      env:
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_DB: test_db
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        ALLOWED_HOSTS: "*"
        ALLOWED_ORIGINS: "*"
        LOG_LEVEL: "INFO"
        TESTING: "1"
      run: |
        cd backend/api
        poetry run python -m unittest tests/tools_test.py -v
        
    - name: Run pytest with coverage
      env:
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_DB: test_db
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        ALLOWED_HOSTS: "*"
        ALLOWED_ORIGINS: "*"
        LOG_LEVEL: "INFO"
        TESTING: "1"
      run: |
        cd backend/api
        poetry run pytest --cov=app --cov-report=xml --cov-report=term-missing tests/
        
    - name: Upload coverage to Codecov
      continue-on-error: true
      uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457  # v3.1.6
      with:
        file: ./backend/api/coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ${{ github.repository }}
        directory: ./backend/api/
        verbose: true

    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      continue-on-error: true
      uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457
      with:
        file: ./backend/api/coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ${{ github.repository }}
        directory: ./backend/api/
        comment: true
        verbose: true

  build-frontend:
    name: Build Frontend Image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.frontend == 'true'
    needs: [changes, frontend-checks, security]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c

      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker metadata for Frontend
        id: meta-frontend
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c
        with:
          images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build Frontend
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: ./mycelium
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:buildcache,mode=max

  build-api:
    name: Build API Image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.api == 'true'
    needs: [changes, api-checks, security]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c

      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker metadata for API
        id: meta-api
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build API
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: ./backend/api
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.API_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.API_IMAGE }}:buildcache,mode=max

  build-keycloak:
    name: Build Keycloak Image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.keycloak == 'true'
    needs: [changes, keycloak-checks, security]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c

      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker metadata for Keycloak
        id: meta-keycloak
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c
        with:
          images: ${{ env.REGISTRY }}/${{ env.KEYCLOAK_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build Keycloak
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: ./backend/keycloak
          push: true
          tags: ${{ steps.meta-keycloak.outputs.tags }}
          labels: ${{ steps.meta-keycloak.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.KEYCLOAK_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.KEYCLOAK_IMAGE }}:buildcache,mode=max

  build-database:
    name: Build Database Image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.database == 'true'
    needs: [changes, security]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c

      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker metadata for Database
        id: meta-database
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c
        with:
          images: ${{ env.REGISTRY }}/${{ env.DB_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build Database
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: ./backend/database
          push: true
          tags: ${{ steps.meta-database.outputs.tags }}
          labels: ${{ steps.meta-database.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.DB_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.DB_IMAGE }}:buildcache,mode=max

