name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true  # Remove labels when files are reverted

# Backend related changes
backend:
- changed-files:
  - any-glob-to-any-file: 'backend/**/*'

# Frontend related changes
frontend:
- changed-files:
  - any-glob-to-any-file: 'frontend/**/*'

# Database related changes
database:
- changed-files:
  - any-glob-to-any-file:
    - 'backend/database/**/*'
    - '**/migrations/**/*'
    - '**/models/**/*'
    - '**/*.sql'

# Documentation changes
documentation:
- changed-files:
  - any-glob-to-any-file: 
    - '**/*.md'
    - '**/*.rst'
    - 'docs/**/*'

# Configuration changes
config:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.yml'
    - '**/*.yaml'
    - '**/*.json'
    - '**/*.toml'
    - '**/*.ini'
    - '.env*'

# Docker related changes
docker:
- changed-files:
  - any-glob-to-any-file:
    - '**/Dockerfile'
    - '**/docker-compose*.yml'
    - '**/docker-compose*.yaml'
    - '.dockerignore'

# CI/CD changes
ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'

# Dependencies updates
dependencies:
- changed-files:
  - any-glob-to-any-file:
    - '**/requirements.txt'
    - '**/requirements/*.txt'
    - '**/poetry.lock'
    - '**/pyproject.toml'
    - '**/package.json'
    - '**/package-lock.json'
    - '**/yarn.lock'

# Security related changes
security:
- changed-files:
  - any-glob-to-any-file:
    - '**/security/**/*'
    - '**/auth/**/*'
    - '**/authentication/**/*'
    - '**/authorization/**/*'

# Testing related changes
testing:
- changed-files:
  - any-glob-to-any-file:
    - '**/tests/**/*'
    - '**/*_test.py'
    - '**/*.spec.ts'
    - '**/*.test.ts'
    - '**/*.spec.js'
    - '**/*.test.js'

# API related changes
api:
- changed-files:
  - any-glob-to-any-file:
    - '**/api/**/*'
    - '**/routes/**/*'
    - '**/endpoints/**/*'
    - '**/controllers/**/*'

# Feature branches
feature:
- head-branch: ['^feature', 'feature']

# Bugfix branches
bugfix:
- head-branch: ['^fix', 'fix', '^bug', 'bug']

# Release branches
release:
- base-branch: ['main', 'master']
- head-branch: ['^release', 'release']
