name: Maintenance

# Add default permissions for all jobs
permissions: {}  # Default to no permissions

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:

jobs:
  cleanup-old-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only needs to read repository contents
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Delete old container images
        run: |
          # List of images to clean
          IMAGES=("myceliumai/frontend" "myceliumai/api" "myceliumai/keycloak" "myceliumai/database")
          
          for IMAGE in "${IMAGES[@]}"; do
            echo "Cleaning up old untagged images for $IMAGE"
            # Get list of digests for untagged images
            DIGESTS=$(curl -s -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" \
              "https://hub.docker.com/v2/repositories/${IMAGE}/tags/?page_size=100" | \
              jq -r '.results[] | select(.tag == null) | .digest')
            
            # Delete each untagged digest
            for DIGEST in $DIGESTS; do
              echo "Deleting digest: $DIGEST"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" \
                "https://hub.docker.com/v2/repositories/${IMAGE}/tags/${DIGEST}/"
            done
          done

  dependency-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Needed to create branches
      pull-requests: write # Needed to create PRs
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Create Dependabot PR for Frontend
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/mycelium"
          package-ecosystem: "npm"
          schedule-interval: "weekly"

      - name: Create Dependabot PR for Backend
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/backend"
          package-ecosystem: "pip"
          schedule-interval: "weekly" 