name: Maintenance

on:
  schedule:
    - cron: '0 0 * * 0'  # Tous les dimanches à minuit
  workflow_dispatch:

jobs:
  cleanup-old-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@0d39a63126868f5eefaa47169615edd3c0f61e20
        with:
          package-name: ${{ github.repository }}
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: true

  dependency-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Create Dependabot PR for Frontend
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/mycelium"
          package-ecosystem: "npm"
          schedule-interval: "weekly"

      - name: Create Dependabot PR for Backend
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/backend"
          package-ecosystem: "pip"
          schedule-interval: "weekly" 