name: Maintenance

# Add default permissions for all jobs
permissions: {}  # Default to no permissions

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:

jobs:
  cleanup-old-images:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d  # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Delete old container images
        run: |
          # List of images to clean
          IMAGES=("myceliumai/frontend" "myceliumai/api" "myceliumai/keycloak" "myceliumai/database")
          
          for IMAGE in "${IMAGES[@]}"; do
            echo "Cleaning up old untagged images for $IMAGE"
            # Get list of digests for untagged images
            DIGESTS=$(curl -s -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" \
              "https://hub.docker.com/v2/repositories/${IMAGE}/tags/?page_size=100" | \
              jq -r '.results[] | select(.tag == null) | .digest')
            
            # Delete each untagged digest
            for DIGEST in $DIGESTS; do
              echo "Deleting digest: $DIGEST"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" \
                "https://hub.docker.com/v2/repositories/${IMAGE}/tags/${DIGEST}/"
            done
          done

  dependency-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Needed to create branches
      pull-requests: write # Needed to create PRs
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d  # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Dependabot PR for Frontend
        uses: dependabot/fetch-metadata@c9c4182bf1b97f5224aee3906fd373f6b61b4526  # v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dependabot PR for Backend
        uses: dependabot/fetch-metadata@c9c4182bf1b97f5224aee3906fd373f6b61b4526  # v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 